apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage

spec:
  
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs01
    path: "/mysql"



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
spec:
  
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
data:
  password: YWRtaW4=
  
  
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-storage
  
  
  
  

  
  
  